name: dravida
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.2.2
  flutter_html: ^3.0.0-beta.2  # For rendering rich text
  google_fonts: ^6.1.0
  uuid: ^4.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  flutter_svg: ^2.1.0
  firebase_ui_auth: ^1.16.1
  flutter_signin_button: ^2.0.0
  marquee: ^2.2.3  # Check for the latest version on pub.dev

  flutter_tts: ^3.7.0  # Check for latest version on pub.dev
  audioplayers: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  fonts:
    - family: NotoSerifKannada
      fonts:
        - asset: assets/fonts/NotoSerifKannada-Regular.ttf
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff" # Background color for Android Adaptive Icons
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true # Ensures iOS icons are correctly formatted