// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGg-8Sh-W3e_0qeR15Z5yVbyFH9QAeTcM',
    appId: '1:519353208327:web:05ae8cd19c886f841e64a2',
    messagingSenderId: '519353208327',
    projectId: 'dravida-99dda',
    authDomain: 'dravida-99dda.firebaseapp.com',
    storageBucket: 'dravida-99dda.firebasestorage.app',
    measurementId: 'G-EYQ2WT10DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rSyRhkBbLcTTVa-FaqoTB_2RprBJiS4',
    appId: '1:519353208327:android:b8e4ebf2d034ed891e64a2',
    messagingSenderId: '519353208327',
    projectId: 'dravida-99dda',
    storageBucket: 'dravida-99dda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIGZMIpKTSl81AE9QFDiRDO5-DS_lVMQ',
    appId: '1:519353208327:ios:3ec4ae51191dc6b81e64a2',
    messagingSenderId: '519353208327',
    projectId: 'dravida-99dda',
    storageBucket: 'dravida-99dda.firebasestorage.app',
    iosClientId: '519353208327-d69th73k0vb9sqsrq52c9qubkf1619on.apps.googleusercontent.com',
    iosBundleId: 'com.example.dravida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZIGZMIpKTSl81AE9QFDiRDO5-DS_lVMQ',
    appId: '1:519353208327:ios:3ec4ae51191dc6b81e64a2',
    messagingSenderId: '519353208327',
    projectId: 'dravida-99dda',
    storageBucket: 'dravida-99dda.firebasestorage.app',
    iosClientId: '519353208327-d69th73k0vb9sqsrq52c9qubkf1619on.apps.googleusercontent.com',
    iosBundleId: 'com.example.dravida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGg-8Sh-W3e_0qeR15Z5yVbyFH9QAeTcM',
    appId: '1:519353208327:web:5732fd117373c2431e64a2',
    messagingSenderId: '519353208327',
    projectId: 'dravida-99dda',
    authDomain: 'dravida-99dda.firebaseapp.com',
    storageBucket: 'dravida-99dda.firebasestorage.app',
    measurementId: 'G-XB30LL4FHE',
  );
}
